# Generated by Django 3.2.8 on 2021-12-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_receiver_profile', to='chat.profile', verbose_name='Получатель')),
                ('request_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_sender_profile', to='chat.profile', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Заявка в друзья',
                'verbose_name_plural': 'Заявки в друзья',
            },
        ),
    ]
