# Generated by Django 3.2.8 on 2021-12-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_profile_avatar'),
        ('chat', '0006_friendrequest_created_at'),
    ]

    operations = [
    ]
