# Generated by Django 3.2.8 on 2021-12-22 15:40

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_was_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Сообщение'),
        ),
    ]
